# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mmmjj
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
baseurl: ""
url: "https://mmmjj.github.io"
permalink: /:year/:month/:day/:title
repository: 
paginate: 5

# Minjung specific configurations
github_profile: "https://github.com/mmmjj"
user: "Minjung Jung"
user_email: "mmmj.dev@gmail.com"
contact_url: "https://docs.google.com/forms/d/e/1FAIpQLSfarEzbTSqkV7fRlYp3ZBDt2zlYsgd5Y9oO5pLn6EKxYLYhRA/viewform?usp=pp_url"
google_tracking_id: "UA-161612590-1"
google_site_verification: "UA-161612590-1"
disqus_shortname: "mmmjj"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true